source 'https://rubygems.org'

# Use Solr
gem 'sunspot_rails', '2.1.0'
gem 'sunspot_solr',	'2.1.0'
gem 'sunspot', '2.1.0'
gem 'progress_bar', '1.0.0'

# for tag
gem 'acts-as-taggable-on'

gem 'rmagick'
gem 'kmeans-clustering', :git => 'git://github.com/vaneyckt/kmeans-clustering.git'

gem 'spring'
gem 'jazz_hands'
gem 'nokogiri'
gem 'fastimage'
gem 'ruby-filemagic'
gem 'ruby-readability'
gem 'railroady'

gem 'rails', '4.1.1'

gem 'mysql2'

gem 'sass-rails', '~> 4.0.2'
gem 'compass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'omniauth-twitter'
gem 'twitter'
gem 'seed_dump'
gem 'font-awesome-rails'
gem 'imgkit'
gem 'bitly'
gem 'newrelic_rpm'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'sqlite3'
end

group :doc do
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
